version: "3.4"

services:

  server:
    image: myback
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - backend

  client:
    image: myfront
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
    networks:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
        - MYSQL_DATABASE=diyar_moein_ca6
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_PORT=33060
    ports:
        - "33060:3306"
    networks:
      - backend

networks:
  backend:
